<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h4>Witaj użytkowniku o loginie: ${email}</h4>
<h4>Zresetuj swoje hasło do konta wchodząc na podany poniżej link</h4>

--------------------------------------------------------------------------------------------------------<br>


<a href="http://localhost:8080/api/user/reset/${id}/${token}" >Aktywacja Konta</a>


--------------------------------------------------------------------------------------------------------<br>


</body>
</html>